<a href="https://colab.research.google.com/github/JoonYoung-Sohn/practice/blob/master/Disease%20Prediction/201228_data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

세가지 데이터셋 병합한 것 마지막으로 정리

normalization (year, person_id 빼고)

array로 변환

In [18]:
from google.colab import drive
drive.mount('/gdrive', force_remount=True)
import pandas as pd
import numpy as np

Mounted at /gdrive

In [19]:
df=pd.read_csv('/gdrive/My Drive/Disease Prediction/total_merge_v3.csv')
df.head()

   YEAR  SEX   AGE  PERSON_ID  HEIGHT  ...  H25-26  H40-42  K20-31  K58  K70
0  2002    2  96.0   10081483   133.0  ...     0.0     0.0     1.0  0.0  0.0
1  2002    2  94.0   10151226   146.0  ...     0.0     0.0     1.0  0.0  0.0
2  2002    2  94.0   10174763   133.0  ...     0.0     0.0     1.0  1.0  0.0
3  2002    2  94.0   10174878   143.0  ...     0.0     0.0     1.0  0.0  0.0
4  2002    2  94.0   10210673   133.0  ...     1.0     0.0     1.0  0.0  0.0

[5 rows x 48 columns]

In [7]:
disease_list = ['C16','C18','C34','H25-26','H40-42','K20-31','K58','K70']
remove_list =[]
before_id = id = df['YEAR'][0]+df['PERSON_ID'][0]
for i in range(len(df)-1):
  id = df['YEAR'][i+1]+df['PERSON_ID'][i+1]
  if id == before_id:
    remove_list.append(i)
    for d in disease_list:
      df[d][i+1] += df[d][i]
  else:
    before_id = id
df_drop = df.drop(df.index[remove_list])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

In [8]:
df_drop

         YEAR  SEX   AGE  PERSON_ID  HEIGHT  ...  H25-26  H40-42  K20-31  K58  K70
0        2002    2  96.0   10081483   133.0  ...     0.0     0.0     1.0  0.0  0.0
1        2002    2  94.0   10151226   146.0  ...     0.0     0.0     1.0  0.0  0.0
3        2002    2  94.0   10174763   133.0  ...     0.0     0.0     1.0  1.0  0.0
4        2002    2  94.0   10174878   143.0  ...     0.0     0.0     1.0  0.0  0.0
6        2002    2  94.0   10210673   133.0  ...     1.0     0.0     1.0  0.0  0.0
...       ...  ...   ...        ...     ...  ...     ...     ...     ...  ...  ...
1088152  2013    2  71.0   99919183   148.0  ...     1.0     0.0     1.0  0.0  0.0
1088155  2013    2  71.0   99943383   151.0  ...     1.0     0.0     1.0  1.0  0.0
1088156  2013    1  71.0   99953556   163.0  ...     0.0     0.0     1.0  0.0  0.0
1088157  2013    1  71.0   99954714   169.0  ...     0.0     0.0     1.0  0.0  0.0
1088158  2013    2  71.0   99960248   159.0  ...     0.0     0.0     1.0  0.0  0.0

[747364 rows x 48 columns]

In [10]:
df_drop.to_csv('/gdrive/My Drive/Disease Prediction/total_merge_v3.csv', header=True, index = False)

In [16]:
max(df_drop['AGE'])

114.0

In [17]:
df_drop.sort_values(by=['PERSON_ID'])

         YEAR  SEX    AGE  PERSON_ID  HEIGHT  ...  H25-26  H40-42  K20-31  K58  K70
509441   2004    2  104.0   10000957   140.0  ...     1.0     0.0     0.0  0.0  0.0
1028196  2010    2  109.0   10011495   150.0  ...     1.0     0.0     1.0  0.0  0.0
1028197  2011    2  110.0   10011495   154.0  ...     0.0     0.0     1.0  0.0  0.0
509442   2008    2  104.0   10036926   142.0  ...     0.0     0.0     1.0  0.0  0.0
875233   2011    2  107.0   10037442   147.0  ...     0.0     0.0     1.0  0.0  0.0
...       ...  ...    ...        ...     ...  ...     ...     ...     ...  ...  ...
509438   2004    2   62.0   99985218   152.0  ...     0.0     0.0     1.0  0.0  0.0
509437   2003    2   61.0   99985218   153.0  ...     1.0     0.0     0.0  1.0  0.0
981383   2008    2  114.0   99988001   149.0  ...     1.0     0.0     0.0  0.0  0.0
937097   2011    2  114.0   99989993   146.0  ...     2.0     1.0     1.0  0.0  0.0
509440   2003    2  104.0   99994476   153.0  ...     0.0     0.0     1.0  1.0  0.0

[747364 rows x 48 columns]

In [21]:
df.columns

Index(['YEAR', 'SEX', 'AGE', 'PERSON_ID', 'HEIGHT', 'WEIGHT', 'BP_HIGH',
       'BP_LWST', 'BLDS', 'TOT_CHOLE', 'HMG', 'OLIG_PROTE_CD', 'SGOT_AST',
       'SGPT_ALT', 'GAMMA_GTP', 'FMLY_HPRTS_PATIEN_YN', 'FMLY_APOP_PATIEN_YN',
       'FMLY_HDISE_PATIEN_YN', 'FMLY_DIABML_PATIEN_YN',
       'FMLY_CANCER_PATIEN_YN', 'SMK_STAT_TYPE_RSPS_CD', 'SMK_TERM_RSPS_CD',
       'DSQTY_RSPS_CD', 'DRNK_HABIT_RSPS_CD', 'TM1_DRKQTY_RSPS_CD',
       'HCHK_APOP_PMH_YN', 'HCHK_HDISE_PMH_YN', 'HCHK_HPRTS_PMH_YN',
       'HCHK_DIABML_PMH_YN', 'HCHK_HPLPDM_PMH_YN', 'HCHK_ETCDSE_PMH_YN',
       'HCHK_PHSS_PMH_YN', 'DFAB_1', 'DFAB_2', 'DFAB_3', 'DFAB_4', 'DFAB_5',
       'DFAB_6', 'DFAB_7', 'DFAB_9', 'C16', 'C18', 'C34', 'H25-26', 'H40-42',
       'K20-31', 'K58', 'K70'],
      dtype='object')

In [22]:
norm_target = ['SEX', 'AGE', 'HEIGHT', 'WEIGHT', 'BP_HIGH',
       'BP_LWST', 'BLDS', 'TOT_CHOLE', 'HMG', 'OLIG_PROTE_CD', 'SGOT_AST',
       'SGPT_ALT', 'GAMMA_GTP', 'SMK_STAT_TYPE_RSPS_CD', 'SMK_TERM_RSPS_CD',
       'DSQTY_RSPS_CD', 'DRNK_HABIT_RSPS_CD', 'TM1_DRKQTY_RSPS_CD']

for t in norm_target:
  t_max = max(df[t])
  t_min = min(df[t])
  for i in range(len(df)):
    df[t][i] = (df[t][i]-t_min)/(t_max-t_min)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [23]:
df

        YEAR  SEX       AGE  PERSON_ID  ...  H40-42  K20-31  K58  K70
0       2002    1  0.666667   10081483  ...     0.0     1.0  0.0  0.0
1       2002    1  0.629630   10151226  ...     0.0     1.0  0.0  0.0
2       2002    1  0.629630   10174763  ...     0.0     1.0  1.0  0.0
3       2002    1  0.629630   10174878  ...     0.0     1.0  0.0  0.0
4       2002    1  0.629630   10210673  ...     0.0     1.0  0.0  0.0
...      ...  ...       ...        ...  ...     ...     ...  ...  ...
747359  2013    1  0.203704   99919183  ...     0.0     1.0  0.0  0.0
747360  2013    1  0.203704   99943383  ...     0.0     1.0  1.0  0.0
747361  2013    0  0.203704   99953556  ...     0.0     1.0  0.0  0.0
747362  2013    0  0.203704   99954714  ...     0.0     1.0  0.0  0.0
747363  2013    1  0.203704   99960248  ...     0.0     1.0  0.0  0.0

[747364 rows x 48 columns]

In [28]:
'''
import sys
ID_dic = {}
for i in range(len(df)):
  if df['PERSON_ID'][i] not in ID_dic:
    ID_dic[df['PERSON_ID'][i]] = []
  ID_dic[df['PERSON_ID'][i]].append((df.loc[i]).to_numpy())
  #print(df.loc[i])
  #print(ID_dic)
  #sys.exit()
'''

In [36]:
number=[]
for key in ID_dic:
  number.append(len(ID_dic[key]))
print(set(number))

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}

In [49]:
## dataframe to dictionary
import sys
ID_dic = {}

for i in range(len(df)):
  if df['PERSON_ID'][i] not in ID_dic:
    ID_dic[df['PERSON_ID'][i]] = {}
  year = int((df.loc[i]).to_numpy()[0])
  value = np.delete((df.loc[i]).to_numpy()[1:],2)
  ID_dic[df['PERSON_ID'][i]][year] = value
  #print(df.loc[i])
  #print(ID_dic)
  #sys.exit()

In [50]:
ID_dic[10011495]

{2010: array([1.        , 0.90740741, 0.40163934, 0.14864865, 0.24291498,
        0.19736842, 0.05652621, 0.12716175, 0.310347  , 0.        ,
        0.00696436, 0.00701403, 0.00601202, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.01298701, 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        , 1.        , 0.        ,
        0.        ]),
 2011: array([1.        , 0.92592593, 0.43442623, 0.15540541, 0.24291498,
        0.32894737, 0.04522097, 0.10579858, 0.37062429, 0.        ,
        0.00573535, 0.00300601, 0.00501002, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.01298701, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        ])}

In [54]:
## dictionary to matrix
import sys

data_set=[]
for key in ID_dic: #10011495
  for key2 in ID_dic[key]: #2010
    arr = np.empty((0,46), float)
    for i in range(5): #2006, 2007...2010
      if key2-4+i in ID_dic[key]:
        arr = np.append(arr, [ID_dic[key][key2]],axis=0)
      else:
        arr = np.append(arr, [np.zeros(46)],axis=0)
    data_set.append(arr)
  #print(data_set)
  #sys.exit()

In [56]:
len(data_set)

747364

- 여기서부터 RNN test

In [57]:
df_array = df[['SEX', 'AGE', 'HEIGHT', 'WEIGHT', 'BP_HIGH',
       'BP_LWST', 'BLDS', 'TOT_CHOLE', 'HMG', 'OLIG_PROTE_CD', 'SGOT_AST',
       'SGPT_ALT', 'GAMMA_GTP', 'FMLY_HPRTS_PATIEN_YN', 'FMLY_APOP_PATIEN_YN',
       'FMLY_HDISE_PATIEN_YN', 'FMLY_DIABML_PATIEN_YN',
       'FMLY_CANCER_PATIEN_YN', 'SMK_STAT_TYPE_RSPS_CD', 'SMK_TERM_RSPS_CD',
       'DSQTY_RSPS_CD', 'DRNK_HABIT_RSPS_CD', 'TM1_DRKQTY_RSPS_CD',
       'HCHK_APOP_PMH_YN', 'HCHK_HDISE_PMH_YN', 'HCHK_HPRTS_PMH_YN',
       'HCHK_DIABML_PMH_YN', 'HCHK_HPLPDM_PMH_YN', 'HCHK_ETCDSE_PMH_YN',
       'HCHK_PHSS_PMH_YN', 'DFAB_1', 'DFAB_2', 'DFAB_3', 'DFAB_4', 'DFAB_5',
       'DFAB_6', 'DFAB_7', 'DFAB_9', 'C16', 'C18', 'C34', 'H25-26', 'H40-42',
       'K20-31', 'K58', 'K70']]

In [58]:
df_array = df_array.to_numpy()

In [59]:
df_array

array([[1.        , 0.66666667, 0.26229508, ..., 1.        , 0.        ,
        0.        ],
       [1.        , 0.62962963, 0.36885246, ..., 1.        , 0.        ,
        0.        ],
       [1.        , 0.62962963, 0.26229508, ..., 1.        , 1.        ,
        0.        ],
       ...,
       [0.        , 0.2037037 , 0.50819672, ..., 1.        , 0.        ,
        0.        ],
       [0.        , 0.2037037 , 0.55737705, ..., 1.        , 0.        ,
        0.        ],
       [1.        , 0.2037037 , 0.47540984, ..., 1.        , 0.        ,
        0.        ]])

In [62]:
disease = 43 # K20-31
y = df_array[:,disease]
X = np.append(df_array[:,:disease],df_array[:,disease+1:],axis=1)

print(X)
print(y)

[[1.         0.66666667 0.26229508 ... 0.         0.         0.        ]
 [1.         0.62962963 0.36885246 ... 0.         0.         0.        ]
 [1.         0.62962963 0.26229508 ... 0.         1.         0.        ]
 ...
 [0.         0.2037037  0.50819672 ... 0.         0.         0.        ]
 [0.         0.2037037  0.55737705 ... 0.         0.         0.        ]
 [1.         0.2037037  0.47540984 ... 0.         0.         0.        ]]
[1. 1. 1. ... 1. 1. 1.]

In [63]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state=1234)

In [71]:
from tensorflow.keras.layers import Dense, GRU, Embedding
from tensorflow.keras.models import Sequential

In [72]:
model = Sequential()
model.add(Embedding(45, 100))
model.add(GRU(128))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(X_train, y_train, epochs=4, validation_split=0.2)

Epoch 1/4
14948/14948 [==============================] - 653s 44ms/step - loss: -12.7315 - acc: 0.7889 - val_loss: -53.0847 - val_acc: 0.8138
Epoch 2/4
14948/14948 [==============================] - 649s 43ms/step - loss: -69.9584 - acc: 0.7922 - val_loss: -107.8274 - val_acc: 0.7240
Epoch 3/4
14948/14948 [==============================] - 654s 44ms/step - loss: -127.0228 - acc: 0.7908 - val_loss: -161.9657 - val_acc: 0.8130
Epoch 4/4
14948/14948 [==============================] - 651s 44ms/step - loss: -185.2430 - acc: 0.7881 - val_loss: -215.7484 - val_acc: 0.7251

In [ ]:
print("\n 테스트 정확도: %.4f" % (model.evaluate(X_test, y_test)[1]))

2509/4672 [===============>..............] - ETA: 23s - loss: -224.4653 - acc: 0.7251