<a href="https://colab.research.google.com/github/JoonYoung-Sohn/practice/blob/master/Disease%20Prediction/201222_data_preprocessing2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
files.upload()

Saving data_after_2008.csv to data_after_2008.csv

In [2]:
import pandas as pd
df=pd.read_csv('data_after_2008.csv')
df.head()

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (65) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

   Unnamed: 0  year        id  ...  sum_ltc_cost_ins  ltcp_kind3  service
0     3809334  2009  10005315  ...               NaN         NaN      2.0
1     3809335  2009  10005315  ...               NaN         NaN      2.0
2     3809336  2009  10005792  ...         5721750.0         2.0      1.0
3     3809337  2009  10012546  ...        14897380.0         1.0      1.0
4     3809338  2009  10012546  ...        14897380.0         1.0      1.0

[5 rows x 72 columns]

In [13]:
df_clean = df.dropna(axis=0)

In [14]:
print(len(df))
print(len(df_clean))

244925
144099

In [15]:
df_clean.head()

   Unnamed: 0  year        id  ...  sum_ltc_cost_ins  ltcp_kind3  service
2     3809336  2009  10005792  ...         5721750.0         2.0      1.0
3     3809337  2009  10012546  ...        14897380.0         1.0      1.0
4     3809338  2009  10012546  ...        14897380.0         1.0      1.0
7     3809341  2009  10024991  ...         7260890.0         2.0      1.0
8     3809342  2009  10028780  ...         7438930.0         2.0      1.0

[5 rows x 72 columns]

In [16]:
df_clean.duplicated(['year', 'id'], keep='first')

2         False
3         False
4          True
7         False
8         False
          ...
244918    False
244919    False
244920    False
244922    False
244924    False
Length: 144099, dtype: bool

In [17]:
df_clean = df_clean.drop_duplicates(['year','id'], keep='first')

In [18]:
print(len(df_clean))

118995